name: two-tower-MLX
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - pytorch
  - torchvision
  - torchaudio
  - pip
  - pip:
      - more-itertools
      - torchmetrics
